name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 백엔드 빌드
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x back/web/gradlew
    
    - name: Build Spring Boot Project
      run: |
        cd back/web
        ./gradlew build

    # 프론트엔드 빌드
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # 필요한 Node.js 버전

    - name: Create .env file
      run: echo REACT_APP_BACK_URL=${{ vars.EC2_HOST }}:8080 >> front/web/.env
      
    - name: Build React Project
      run: |
        cd front/web
        npm install
        npm run build
      env:
        CI: false

    # AWS EC2 서버로 파일 전송
    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.PEM }}
        port: 22
        source: "back/web/build/libs/*.war, front/web/build"
        target: "/home/ec2-user/path/to/remote/directory"

    # 원격 서버에서 배포 스크립트 실행
    - name: Execute deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.PEM }}
        port: 22
        script: |
          cd /home/ec2-user/path/to/remote/directory/back/web/build/libs
          mv web-0.0.1-SNAPSHOT.war /home/ec2-user/apache-tomcat-9.0.80/webapps/ROOT.war
          sudo systemctl restart nginx
          sudo /home/ec2-user/apache-tomcat-9.0.80/bin/shutdown.sh
          sudo /home/ec2-user/apache-tomcat-9.0.80/bin/startup.sh
          
