name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 백엔드 빌드
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x back/web/gradlew
    
    - name: Build Spring Boot Project
      run: |
        cd back/web
        ./gradlew build
      env:
        DBURL: ${{ secrets.DBURL }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_USER: ${{ secrets.DB_USER }}
        EC2_HOST: ${{vars.EC2_HOST}}
        EC2_PORT: ${{vars.EC2_PORT}}
        FRONT_HOST: ${{vars.FRONT_HOST}}
        FRONT_PORT: ${{vars.FRONT_PORT}}
        JWT_KEY: ${{secrets.JWT_KEY}}
        REDIS_HOST: ${{vars.REDIS_HOST}}
        REDIS_PORT: ${{vars.REDIS_PORT}}

    # 프론트엔드 빌드
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # 필요한 Node.js 버전

    - name: Build React Project
      run: |
        cd front/web
        npm install
        npm run build
      env:
        CI: false

    # AWS EC2 서버로 파일 전송
    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.PEM }}
        port: 22
        source: "back/web/build/libs/*.war, front/web/build"
        target: "/home/ec2-user/path/to/remote/directory"

    # # 원격 서버에서 배포 스크립트 실행
    # - name: Execute deployment script
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USERNAME }}
    #     key: ${{ secrets.EC2_SSH_KEY }}
    #     port: 22
    #     script: |
    #       # 백엔드 및 프론트엔드 배포 스크립트
